### ISSUE TITLE
Scopes

### ISSUE THREAD

**Issue by Idered** [Syncano/syncano-server-js#98]
```yaml
models:
  post:
    scope:
      - name: published
        column: published
        is: >
        value: true
      - name: unpublished
        column: published
        value: false
```

```js
data.post.published().list()
```
